endpoints:
  - url: https://google.com
    display_name: 'Google'
  - url: https://yahoo.com
    display_name: 'Yahoo!'
  - url: https://notworking
  - url: https://discord.com
    display_name: 'Discord'
  - url: https://cnn.com
    display_name: 'CNN'
  - url: 192.168.50.1
    display_name: 'Local Thing'

#display name optional
#how often to ping duh
ping_frequency: 10

#Alerting 
#Enable alerting and the type of alert
#conseq failures is how many in a row to trigger alerts
#cooldown is how long before sending another alert
alerting:
  enabled: true
  consecutive_failures_threshold: 6
  cooldown_duration: 60
  pagerduty:
    enabled: false
    api_key: YOUR_PAGERDUTY_API_KEY
    service_id: YOUR_SERVICE_ID
  opsgenie:
    enabled: false
    api_key: YOUR_OPSGENIE_API_KEY
  slack:
    enabled: true
    webhook_url: https://hooks.slack.com/services/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
    channel: alerts-channel
  telegram:
    enabled: false
    bot_token: YOUR_TELEGRAM_BOT_TOKEN
    chat_id: YOUR_TELEGRAM_CHAT_ID
  discord:
    enabled: false
    webhook_url: YOUR_DISCORD_WEBHOOK_URL