endpoints:
  - https://google.com
  - https://github.com
  - https://exam

#How often to ping in seconds
ping_interval: 10

#Alerting 
alerting:
  enabled: true
  consecutive_failures_threshold: 6
  cooldown_duration: 20
  pagerduty:
    enabled: false
    api_key: YOUR_PAGERDUTY_API_KEY
  opsgenie:
    enabled: false
    api_key: YOUR_OPSGENIE_API_KEY
  slack:
    enabled: true
    webhook_url: https://hooks.slack.com/services/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
    channel: alerts-channel
  telegram:
    enabled: false
    bot_token: YOUR_TELEGRAM_BOT_TOKEN
    chat_id: YOUR_TELEGRAM_CHAT_ID
  discord:
    enabled: false
    webhook_url: YOUR_DISCORD_WEBHOOK_URL